select    "PER_PERSON_NAMES_F"."LAST_NAME"
from	"FUSION"."PER_PERSON_NAMES_F" "PER_PERSON_NAMES_F",
	"FUSION"."PER_PERIODS_OF_SERVICE" "PER_PERIODS_OF_SERVICE" 
 where   "PER_PERIODS_OF_SERVICE"."PERSON_ID"="PER_PERSON_NAMES_F"."PERSON_ID"
  and 	 "PER_PERSON_NAMES_F"."NAME_TYPE" ='GLOBAL' and
"PER_PERSON_NAMES_F"."LAST_NAME"||' '||"PER_PERSON_NAMES_F"."FIRST_NAME"||' '||"PER_PERSON_NAMES_F"."MIDDLE_NAMES" = :fio
and  to_char("PER_PERIODS_OF_SERVICE"."ATTRIBUTE_DATE1", 'DD.MM.YYYY')||'/'||"PER_PERIODS_OF_SERVICE"."ATTRIBUTE2" = :orderDateNumber