select 
"PER_PERIODS_OF_SERVICE"."DATE_START",

(select "ANC_PER_ACCRUAL_ENTRIES"."END_BAL"  from "FUSION"."ANC_PER_ACCRUAL_ENTRIES"  "ANC_PER_ACCRUAL_ENTRIES" where "ANC_PER_ACCRUAL_ENTRIES"."PERSON_ID" = "PER_PERIODS_OF_SERVICE"."PERSON_ID"
AND "ANC_PER_ACCRUAL_ENTRIES"."PLAN_ID" = 300000001648035
AND TO_CHAR("ANC_PER_ACCRUAL_ENTRIES"."ACCRUAL_PERIOD",'DD.MM.YYYY') = TO_CHAR("PER_PERIODS_OF_SERVICE"."ACTUAL_TERMINATION_DATE",'DD.MM.YYYY')
)  END_BAL,


"PER_PERIODS_OF_SERVICE"."ACTUAL_TERMINATION_DATE"-(
(select "ANC_PER_ACCRUAL_ENTRIES"."END_BAL"  from "FUSION"."ANC_PER_ACCRUAL_ENTRIES"  "ANC_PER_ACCRUAL_ENTRIES" where "ANC_PER_ACCRUAL_ENTRIES"."PERSON_ID" = "PER_PERIODS_OF_SERVICE"."PERSON_ID"
AND "ANC_PER_ACCRUAL_ENTRIES"."PLAN_ID" = 300000001648035
AND TO_CHAR("ANC_PER_ACCRUAL_ENTRIES"."ACCRUAL_PERIOD",'DD.MM.YYYY') = TO_CHAR("PER_PERIODS_OF_SERVICE"."ACTUAL_TERMINATION_DATE",'DD.MM.YYYY')
)*12
) PER_DATE



from	"FUSION"."PER_PERSON_NAMES_F" "PER_PERSON_NAMES_F",
	"FUSION"."PER_PERIODS_OF_SERVICE" "PER_PERIODS_OF_SERVICE"
        
       
where   "PER_PERIODS_OF_SERVICE"."PERSON_ID"="PER_PERSON_NAMES_F"."PERSON_ID"
and 	 "PER_PERSON_NAMES_F"."NAME_TYPE" ='GLOBAL' 
and   "PER_PERSON_NAMES_F"."LAST_NAME"||' '||"PER_PERSON_NAMES_F"."FIRST_NAME"||' '||"PER_PERSON_NAMES_F"."MIDDLE_NAMES" = :fio
and    to_char("PER_PERIODS_OF_SERVICE"."ATTRIBUTE_DATE1", 'DD.MM.YYYY')||'/'||"PER_PERIODS_OF_SERVICE"."ATTRIBUTE2" = :orderDateNumber