select "PER_PERSON_NAMES_F_V"."FIRST_NAME" as "FIRST_NAME", 

 "PER_PERSON_NAMES_F_V"."LAST_NAME" as "LAST_NAME", 

 "PER_PERSON_NAMES_F_V"."DISPLAY_NAME" as "DISPLAY_NAME", 

 "PER_PERSON_NAMES_F_V"."MIDDLE_NAMES" as "MIDDLE_NAME", 

 "PER_PERSON_NAMES_F_V"."PERSON_ID" as "PERSON_ID"

 from "PER_PERSON_NAMES_F_V" "PER_PERSON_NAMES_F_V"

 where  SYSDATE BETWEEN "PER_PERSON_NAMES_F_V"."EFFECTIVE_START_DATE"(+) AND 

"PER_PERSON_NAMES_F_V"."EFFECTIVE_END_DATE"(+)